# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_on', models.DateTimeField()),
                ('forecasting', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TimeRange')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='base.Location'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='base.Type'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.Length'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.Location'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='timerange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.TimeRange'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.Type'),
        ),
    ]
