# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accuracy',
            old_name='timerange',
            new_name='time_range',
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.Length'),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.Location'),
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='base.Type'),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TimeRange'),
        ),
    ]
