# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 06:49
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import datetime

from django.utils.timezone import get_current_timezone, make_aware


def create_locations(apps, schema_editor):
    Location = apps.get_model("base", "Location")
    Location.objects.create(
        name="Opava",
        lat=49.9386636,
        lon=17.9025700,
    )

    Location.objects.create(
        name="Brno",
        lat=49.2002211,
        lon=16.6078411,
    )

    Location.objects.create(
        name="Praha",
        lat=50.0835494,
        lon=14.4341414,
    )


def create_types(apps, schema_editor):
    Type = apps.get_model("base", "Type")
    Type.objects.create(
        name="Temperature",
        slug="temp",
    )

    Type.objects.create(
        name="Cloudiness",
        slug="clouds",
    )

    Type.objects.create(
        name="Wind speed",
        slug="wind_speed",
    )

    Type.objects.create(
        name="Precipitation",
        slug="rain_3h",
    )


def create_lengths(apps, schema_editor):
    Length = apps.get_model("base", "Length")
    Length.objects.create(
        name="Actual time",
        length=0,
    )
    Length.objects.create(
        name="3 hours",
        length=3,
    )
    Length.objects.create(
        name="6 hours",
        length=6,
    )
    Length.objects.create(
        name="12 hours",
        length=12,
    )
    Length.objects.create(
        name="1 day",
        length=24,
    )
    Length.objects.create(
        name="2 days",
        length=48,
    )


def create_timerange(apps, schema_editor):
    TimeRange = apps.get_model("base", "TimeRange")

    # top most time range
    TimeRange.objects.create(
        parent_id=None,
        start=make_aware(datetime(2000, 1, 1), get_current_timezone()),
        end=make_aware(datetime(2100, 1, 1), get_current_timezone()),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_auto_20160412_0646'),
    ]

    operations = [
        migrations.RunPython(create_locations),
        migrations.RunPython(create_types),
        migrations.RunPython(create_lengths),
        migrations.RunPython(create_timerange),
    ]
