# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 07:17
from __future__ import unicode_literals

from random import random

from django.db import migrations
from django.utils.datetime_safe import datetime
from django.utils.timezone import make_aware, get_current_timezone


def create_locations(apps, schema_editor):
    Location = apps.get_model("base", "Location")
    Type = apps.get_model("base", "Type")
    Length = apps.get_model("base", "Length")
    Forecast = apps.get_model("base", "Forecast")

    for day in range(3, 30):
        for hour in range(0, 24, 3):
            for location in Location.objects.all():
                for type in Type.objects.all():
                    for length in Length.objects.all():
                        real_day = day
                        real_hour = hour - length.length
                        while real_hour < 0:
                            real_day -= 1
                            real_hour += 24

                        Forecast.objects.create(
                            forecasted_on=make_aware(datetime(2015, 6, real_day, real_hour), get_current_timezone()),
                            forecasting=make_aware(datetime(2015, 6, day, hour), get_current_timezone()),
                            location=location,
                            type=type,
                            value=random() * length.length,
                        )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_auto_20160412_0649'),
    ]

    operations = [
        migrations.RunPython(create_locations),
    ]
