# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160412_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField()),
                ('max', models.FloatField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Type')),
            ],
        ),
    ]
