# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 08:48
from __future__ import unicode_literals

from django.db import migrations


# copied from statistics.py
# and YES, copy and paste is good idea in this case :)
def update_statistics(apps, schema_editor):
    Statistics = apps.get_model("base", "Statistics")
    Type = apps.get_model("base", "Type")
    Forecast = apps.get_model("base", "Forecast")

    for type in Type.objects.all():
        if not Statistics.objects.filter(type=type).exists():
            Statistics.objects.create(
                type=type,
                max=0,
                avg=0,
            )

    for stat in Statistics.objects.all():
        # copied form models.py
        forecasts = Forecast.objects.filter(type=stat.type)

        sum = 0
        max = 0
        count = forecasts.count()
        if count > 0:
            max = forecasts.first().value

        for forecast in forecasts.iterator():  # no cache
            sum += forecast.value
            if forecast.value > max: max = forecast.value

        stat.max = max
        stat.avg = sum / count
        stat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0005_statistics'),
    ]

    operations = [
        migrations.RunPython(update_statistics),
    ]
