# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 08:48
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.aggregates import Avg, Max


# copied from statistics.py
# and YES, copy and paste is good idea in this case :)
def update_statistics(apps, schema_editor):
    Statistics = apps.get_model("base", "Statistics")
    Type = apps.get_model("base", "Type")
    Forecast = apps.get_model("base", "Forecast")

    for type in Type.objects.all():
        if not Statistics.objects.filter(type=type).exists():
            Statistics.objects.create(
                type=type,
                max=0,
                avg=0,
            )

    for stat in Statistics.objects.all():
        # copied form models.py
        forecasts = Forecast.objects.filter(type=stat.type)

        stat.avg = 0
        stat.max = 0
        if forecasts.exists():
            stat.avg = forecasts.aggregate(Avg('value'))['value__avg']
            stat.max = forecasts.aggregate(Max('value'))['value__max']

        stat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0005_statistics'),
    ]

    operations = [
        migrations.RunPython(update_statistics),
    ]
