# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:49
from __future__ import unicode_literals

from datetime import datetime

from django.db import migrations
from django.utils.timezone import make_aware, get_current_timezone

from base.forecast_to_accuracy import forecast_to_accuracy


def count_forecasts(apps, schema_editor):
    return
    # can't run this, i would have to copy it all to migrate file, so run it yourselfs, if you want to
    # for day in range(3, 30):
    #     for hour in range(0, 24, 3):
    #         forecast_to_accuracy(
    #             make_aware(datetime(2015, 6, day, hour), get_current_timezone())
    #         )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160412_2049'),
    ]

    operations = [
        migrations.RunPython(count_forecasts),
    ]
